/**
 * This file is part of DKWG-Events.
 *
 * Copyright (C) 2025 GEO Data and Knowledge Working group members.
 *
 * DKWG-Events is free software; you can redistribute it and/or modify it
 * under the terms of the MIT License; see LICENSE file for more details.
 */

import logoDKWG from '@public/images/logo-dkwg.svg';

export const ODOKSchedule = [
  {
    topic: 'ODOK and Youth',
    title: 'Introduction',
    author: 'Kalamkas Yessimkhanova and Sam Amos',
    organization: 'GEO Secretariat',
    time: '14:00 - 14:05',
    type: 'Presentation',
  },
  {
    topic: 'ODOK and Youth',
    title: 'Ideathon EC - ESA',
    author: 'TBC',
    organization: 'TBC',
    time: '14:05 - 14:12',
    type: 'Presentation',
  },
  {
    topic: 'ODOK and Youth',
    title: 'EarthMonitor: summer schools and workshops',
    author: 'Tom Hengl',
    organization: 'Open Geo Hub',
    time: '14:12 - 14:19',
    type: 'Presentation',
  },
  {
    topic: 'ODOK and Youth',
    title:
      'Capacity building on the construction and applications for global UAV observation network',
    author: 'Yue Huan',
    organization: 'REIS',
    time: '14:19 - 14:26',
    type: 'Presentation',
  },
  {
    topic: 'ODOK and Youth',
    title: 'Testimonial from GEOVersity students on usage of Drones',
    author: 'Lamine Ndiaye ',
    organization: 'HOT-OSM',
    time: '14:26 - 14:33',
    type: 'Presentation',
  },
  {
    topic: 'ODOK and Youth',
    title: 'Discussion time',
    author: 'All speakers',
    organization: 'REIS',
    time: '14:33 - 14:43',
    type: 'Round table',
  },
  {
    topic: 'ODOK and National GEOs',
    title: 'Introduction',
    author: 'Paola de Salvo',
    organization: 'GEO Secretariat',
    time: '14:43 - 14:48',
    type: 'Presentation',
  },
  {
    topic: 'ODOK and National GEOs',
    title: 'An example of Countries cooperation in knowledge exchange',
    author: 'Felipe Carlos',
    organization: 'GEO Secretariat',
    time: '14:48 - 14:55',
    type: 'Presentation',
  },
  {
    topic: 'ODOK and National GEOs',
    title: 'Ghana example of National GEOs Knowledge Hubs',
    author: 'Amos Kabobah',
    organization: 'UENR',
    time: '14:55 - 15:02',
    type: 'Presentation',
  },
  {
    topic: 'ODOK and National GEOs',
    title: ' South Africa example of National GEOs Knowledge Hubs',
    author: 'Lulu Makapela',
    organization: 'CSIR',
    time: '15:02 - 15:09',
    type: 'Presentation',
  },
  {
    topic: 'ODOK and National GEOs',
    title:
      'Energizing EO Capacity Building on Flood and Drought Management: a Community Consultation on the Nexus between SDGs 11 and 17',
    author: 'Lawrence Friedl',
    organization: 'NASA',
    time: '15:16 - 15:23',
    type: 'Presentation',
  },
  {
    topic: 'ODOK and National GEOs',
    title: 'Discussion time',
    author: 'All speakers',
    time: '15:23 - 15:33',
    type: 'Round table',
  },
  {
    topic: 'In situ data in GEO',
    title: 'The GEO In situ data strategy',
    author: 'Helen Glaves',
    organization: 'BGS',
    time: '15:33 - 15:40',
    type: 'Presentation',
  },
  {
    topic: 'In situ data in GEO',
    title: 'Bringing a decentralized approach to trust in GEO data from data spaces',
    author: 'Joan Maso',
    organization: 'University of Barcelona',
    time: '15:40 - 15:47',
    type: 'Presentation',
  },
  {
    topic: 'In situ data in GEO',
    title:
      'An overview of the in-situ data requirements collected among the GEO Work Programme activities. Can providers respond to the user demands?',
    author: 'Alba Brobia',
    organization: 'CREAF',
    time: '15:47 - 15:54',
    type: 'Presentation',
  },
  {
    topic: 'In situ data in GEO',
    title: 'The importance of In-Situ data and how to close existing data gaps',
    author: 'Steffen Fritz',
    organization: 'IIASA',
    time: '15:43 - 16:01',
    type: 'Presentation',
  },
  {
    topic: 'In situ data in GEO',
    title: 'GCOS & In situ Global Climate Data center',
    author: 'Antonio Bombelli',
    organization: 'WMO',
    time: '16:01 - 16:08',
    type: 'Presentation',
  },
  {
    topic: 'In situ data in GEO',
    title: 'Discussion time',
    author: 'All speakers',
    time: '16:08 - 16:18',
    type: 'Round table',
  },
  {
    topic: 'ODOK and new GWP activities',
    title: 'Introduction',
    author: 'Bente Lilja Bye',
    organization: 'BLB',
    time: '16:18 - 16:23',
    type: 'Presentation',
  },
  {
    topic: 'ODOK and new GWP activities',
    title: 'GEO Knowledge Hub the centralized digital library for EO knowledge',
    author: 'GEO Knowledge Hub Team',
    organization: 'GEO Data and Knowledge Working Group',
    time: '16:23 - 16:30',
    type: 'Presentation',
  },
  {
    topic: 'ODOK and new GWP activities',
    title: 'Self Assessment/Libinsitu',
    author: 'Lionel Menard',
    organization: 'MinesParis',
    time: '16:30 - 16:37',
    type: 'Presentation',
  },
  {
    topic: 'ODOK and new GWP activities',
    title: 'G-REQS: Geospatial in-situ Requirements',
    author: 'Joan Maso',
    organization: 'University of Geneva',
    time: '16:37 - 16:44',
    type: 'Presentation',
  },
  {
    topic: 'ODOK and new GWP activities',
    title: 'The GEO data sharing and data management principles & open knowledge',
    author: 'Bente Lilja Bye',
    organization: 'BLB',
    time: '16:44 - 16:51',
    type: 'Presentation',
  },
  {
    topic: 'ODOK and new GWP activities',
    title: 'Data and Software license guidance',
    author: 'Taylor Campbell and Jan Ainali',
    organization: 'Creative Commons',
    time: '16:51 - 16:58',
    type: 'Presentation',
  },
  {
    topic: 'ODOK and new GWP activities',
    title: 'UNCCD implementation demo',
    author: 'Taylor Campbell and Jan Ainali',
    organization: 'Creative Commons',
    time: '16:58 - 17:05',
    type: 'Presentation',
  },
  {
    topic: 'ODOK and new GWP activities',
    title: 'AI and ML in the Americas ',
    author: 'Arif Rustem',
    organization: 'UMBC',
    time: '17:05 - 17:12',
    type: 'Presentation',
  },
  {
    topic: 'ODOK and new GWP activities',
    title: 'Discussion time',
    author: 'All speakers',
    time: '17:12 - 17:22',
    type: 'Round table',
  },
  {
    topic: 'Closing',
    title: 'Final remarks and next steps',
    author: 'All speakers',
    time: '17:22 - 17:30',
    type: 'Presentation',
  },
];

export const BoothSchedule = {
  Day01: {
    title: 'Monday, 5 May',
    description: 'Focusing on Agriculture and Food Security and Water and Land Sustainability',
    activities: [
      {
        topic: 'Activities',
        title: 'Coffee break',
        sponsor: 'Italian Space Agency (ASI)',
        time: '10:30 - 11:00',
        type: 'Coffee break',
      },
      {
        topic: 'Activities',
        title: 'GEO Knowledge Hub',
        author: 'Felipe Carlos and Paola de Salvo',
        organization: 'GEO Secretariat',
        time: '10:30 - 11:00 (during lunch break)',
        type: 'Interactive demo',
      },
      {
        topic: 'Activities',
        title: 'Data Licensing and Software Licensing',
        author: 'Taylor Campbell and Jan Ainali',
        organization: 'Creative Commons',
        time: '11:00 - 11:30',
        type: 'Interactive demo',
      },
      {
        topic: 'Activities',
        title: 'Field boundary delineation',
        author: 'Mykola Lavreniuk and Andrii Shelestov',
        organization: 'Creative Commons',
        time: '11:30 - 12:00',
        type: 'Interactive demo',
      },
      {
        topic: 'Activities',
        title: 'Lunch Break',
        sponsor: 'Italian Space Agency (ASI)',
        time: '12:30 - 14:00',
        type: 'Lunch Break',
      },
      {
        topic: 'Activities',
        title:
          'OpenEarthMonitor - Cloud-free Landsat mosaics for monitoring land cover time series (1997-2022)',
        author: 'Leandro Parente',
        organization: 'Open Geo Hub',
        time: '12:30 - 13:00 (during lunch break)',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'OpenEarthMonitor - demo of the tropical crop monitor',
        author: 'Dainius Masiliunas',
        organization: 'Open Geo Hub',
        time: '13:00 - 13:30 (during lunch break)',
        type: 'Interactive demo',
      },
      {
        topic: 'Activities',
        title: 'Open Data and Open Knowledge Workshop (2025)',
        description:
          'Discover, collaborate, and innovate! Join the ODOK Workshop hosted by the GEO Data and Knowledge Working Group to explore, learn, and share EO-based solutions',
        time: '14:00 - 17:30',
        cta: true,
        ctaLink: '/',
        ctaTagline: 'Learn. Share. Build.',
        ctaLogo: logoDKWG,
        type: 'Special Event',
      },
    ],
  },
  Day02: {
    title: 'Tuesday, 6 May',
    description: 'Focusing on Ecosystem Biodiversity and Carbon Management',
    activities: [
      {
        topic: 'Activities',
        title: 'Coffee break',
        sponsor: 'Italian Space Agency (ASI)',
        time: '9:00 - 9:30',
        type: 'Coffee break',
      },
      {
        topic: 'Activities',
        title: 'Learn all about the  Data Sharing and Data Management Principles',
        author: 'Bente Lilja Bye',
        organization: 'BLB',
        time: '9:00 - 9:30',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Gross Primary Production for Monitoring Ecosystem Health - Product Demo',
        author: 'Ulf Mallast',
        organization: 'TBC',
        time: '9:30 - 10:00',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'GEO Knowledge Hub demo',
        author: 'Felipe Carlos and Paola de Salvo',
        organization: 'GEO Secretariat',
        time: '10:00 - 10:30',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title:
          'OpenEarthMonitor - Ensemble Land Cover 30m 2000-2024 product to support international organizations',
        author: 'Rolf Simoes',
        organization: 'Open Geo Hub',
        time: '10:30 - 11:00 (during coffee break)',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Data Licensing and Software Licensing',
        author: 'Taylor Campbell',
        organization: 'Creative Commons',
        time: '11:00 - 11:30',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Ensuring Data Quality and Management: a case study at the Davos observatory',
        author: 'Jean-Phillipe Montillet',
        organization: 'PMOD/WRC',
        time: '11:30 - 12:00',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Space for Climate Observatory projects',
        author: 'Frédéric Bretar and Alexia Freigneaux',
        organization: 'SCO',
        time: '11:30 - 12:00',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Lunch break',
        sponsor: 'Italian Space Agency (ASI)',
        time: '12:30 - 14:00',
        type: 'Lunch break',
      },
      {
        topic: 'Activities',
        title: 'Learn to become a GEO Knowledge Hub provider',
        author: 'Felipe Carlos and Paola de Salvo',
        organization: 'GEO Secretariat',
        time: '12:30 - 13:00 (during lunch break)',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Global Ecosystem Atlas Demo',
        author: 'David Patterson',
        organization: 'GEO Secretariat',
        time: '14.30 - 15.00',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Data Sharing and Data Management Principles success stories',
        author: 'Bente Lilja Bye',
        organization: 'BLB',
        time: '15:00 - 15:30',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Coffee break',
        sponsor: 'Italian Space Agency (ASI)',
        time: '15:30 - 16:00',
        type: 'Coffee break',
      },
      {
        topic: 'Activities',
        title: 'OpenEarthMonitor - World carbon flux monitor demo (TBC)',
        author: 'Igor Milosavljevic',
        organization: 'Open Earth Monitor Cyberinfrastructure project',
        time: '15:30 - 16:00 (during coffee break)',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'GEO Knowledge Hub for National GEOs - Lets built it together!',
        author: 'Felipe Carlos and Paola de Salvo',
        organization: 'GEO Secretariat',
        time: '16:30 - 17:00',
        type: 'Presentation',
      },
    ],
  },
  Day03: {
    title: 'Wednesday, 7 May',
    description: 'Focusing on Weather Hazard and Disaster Resilience',
    activities: [
      {
        topic: 'Activities',
        title: 'Learn all about the Data Sharing and Data Management Principles',
        author: 'Bente Lilja Bye',
        organization: 'BLB',
        time: '9:00 - 9:30',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'GEO Knowledge Hub',
        author: 'Felipe Carlos and Paola de Salvo',
        organization: 'GEO Secretariat',
        time: '9:30 - 10:00',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Coffee break',
        sponsor: 'Italian Space Agency (ASI)',
        time: '10:00 - 10:30',
        type: 'Coffee break',
      },
      {
        topic: 'Activities',
        title: 'FAO WaPOR open access database',
        author: 'Almutaz Mohammed',
        organization: 'FAO',
        time: '10:00 - 10:45 (during coffee break)',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Ensuring Data Quality and Management: a case study at the Davos observatory (TBC)',
        author: 'Jean-Phillipe Montillet',
        organization: 'PMOD/WRC',
        time: '10:45 - 11:00',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Data Licensing and Software Licensing',
        author: 'Taylor Campbell and Jan Ainali',
        organization: 'Creative Commons',
        time: '11:00 - 11:30',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Service for Drought and Water Depletion',
        author: 'Katarzyna Dabrowska - Zielinska',
        organization: 'Creative Commons',
        time: '11:30 - 12:00',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Lunch break',
        sponsor: 'Italian Space Agency (ASI)',
        time: '12:30 - 14:00',
        type: 'Lunch break',
      },
      {
        topic: 'Activities',
        title: 'Learn to become a GEO Knowledge Hub provider',
        author: 'Felipe Carlos and Paola de Salvo',
        organization: 'GEO Secretariat',
        time: '13:00 - 13:30 (during lunch time)',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Space for Climate Observatory projects',
        author: 'Frédéric Bretar and Alexia Freigneaux',
        organization: 'SCO',
        time: '14:00 - 14:30',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Data Sharing and Data Management Principles success stories',
        author: 'Bente Lilja Bye',
        organization: 'BLB',
        time: '15:00 - 15:30',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Knowledge generation using Earth Observation for the SDGs',
        author: 'Gregory Giuliani',
        organization: 'University of Geneva',
        time: '16:00 - 16:30',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'GEO Knowledge Hub for National GEOs - Lets built it together!',
        author: 'Felipe Carlos and Paola de Salvo',
        organization: 'GEO Secretariat',
        time: '16:30 - 17:00',
        type: 'Presentation',
      },
    ],
  },
  Day04: {
    title: 'Thursday, 8 May',
    description: 'Focusing on Climate, Energy and Urbanization and One Health',
    activities: [
      {
        topic: 'Activities',
        title: 'Learn all about the Data Sharing and Data Management Principles',
        author: 'Bente Lilja Bye',
        organization: 'BLB',
        time: '9:00 - 9:30',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'GEO Knowledge Hub',
        author: 'Felipe Carlos and Paola de Salvo',
        organization: 'GEO Secretariat',
        time: '9:30 - 10:00',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Coffee break',
        sponsor: 'Italian Space Agency (ASI)',
        time: '10:00 - 10:30',
        type: 'Coffee break',
      },
      {
        topic: 'Activities',
        title:
          'OpenEarthMonitor - Ensemble terrain modelling at 30 m resolution data fusion to support hydrological modeling',
        author: 'Tom Hengl',
        organization: 'Open Geo Hub',
        time: '10:00 - 10:30 (during coffee break)',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Space for Climate Observatory projects',
        author: 'Frédéric Bretar and Alexia Freigneaux',
        organization: 'SCO',
        time: '10:30 - 11:00',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Data Licensing and Software Licensing',
        author: 'Taylor Campbell and Jan Ainali',
        organization: 'Creative Commons',
        time: '11:30 - 12:00',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'GCOS Climate Data Strategy',
        author: 'Antonio Bombelli',
        organization: 'GCOS',
        time: '11:30 - 12:00',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Lunch break',
        sponsor: 'Italian Space Agency (ASI)',
        time: '12:30 - 14:00',
        type: 'Lunch break',
      },
      {
        topic: 'Activities',
        title: 'Learn to become a GEO Knowledge Hub provider',
        author: 'Felipe Carlos and Paola de Salvo',
        organization: 'GEO Secretariat',
        time: '12:30 - 13:00 (during lunch break)',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Global Heat Resilience Service: co-design over EI services',
        author: 'Martyn Clark',
        organization: 'GEO Secretariat',
        time: '13:30 - 14:00 (during lunch break)',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'Data Sharing and Data Management Principles success stories',
        author: 'Bente Lilja Bye',
        organization: 'BLB',
        time: '14:30 - 15:00',
        type: 'Presentation',
      },
      {
        topic: 'Activities',
        title: 'GEO Knowledge Hub for National GEOs - Lets built it together!',
        author: 'Felipe Carlos and Paola de Salvo',
        organization: 'GEO Secretariat',
        time: '17:00 - 17:30',
        type: 'Presentation',
      },
    ],
  },
  Day05: {
    title: 'Friday, 9 May',
    description: 'Focusing on Youth',
    activities: [
      {
        topic: 'Activities',
        title: 'GEO Knowledge Hub for youth',
        description:
          'Discover how the GEO Knowledge Hub empowers the next generation of changemakers. This session invites students, early-career professionals, and young innovators to explore open tools, real-world datasets, and collaborative opportunities that support informed action on global challenges.',
        time: '09:00 - 14:00',
        cta: true,
        ctaLink: '#',
        ctaTagline: 'Shape the future',
        ctaLogo: logoDKWG,
        type: 'Special Event',
      },
    ],
  },
};
